# Release lanes
release-lane:operator:
  - changed-files:
      - any-glob-to-any-file:
          - "internal/**"
          - "cmd/**"
          - "ui/**"
          - "Dockerfile"
          - "Dockerfiles/**"
          - "go.mod"
          - "go.sum"

release-lane:chart:
  - changed-files:
      - any-glob-to-any-file:
          - "helm/**"

release-lane:crd:
  - changed-files:
      - any-glob-to-any-file:
          - "api/**"
          - "config/crd/**"

# Areas
area:operator:
  - changed-files:
      - any-glob-to-any-file:
          - "internal/**"
          - "cmd/session-controller/**"

area:server:
  - changed-files:
      - any-glob-to-any-file:
          - "cmd/server/**"

area:ui:
  - changed-files:
      - any-glob-to-any-file:
          - "ui/**"

area:chart:
  - changed-files:
      - any-glob-to-any-file:
          - "helm/**"

area:crd:
  - changed-files:
      - any-glob-to-any-file:
          - "api/**"
          - "config/crd/**"

area:config:
  - changed-files:
      - any-glob-to-any-file:
          - "config/default/**"
          - "config/manager/**"
          - "config/manifests/**"

area:tests:
  - changed-files:
      - any-glob-to-any-file:
          - "test/**"
          - "internal/**/**_test.go"
          - "hack/tests/**"

area:docs:
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - "docs/**"
