# ------------- server ----------------
port: 9090
host: ""
read_timeout: 5
write_timeout: 10

# Allow a separate Vite dev server if you ever run the UI separately
allow_origin: "http://localhost:9090"

# K8s client throttle
kube_qps: 50.0
kube_burst: 100

# Logging
debug: true

# Auth bootstrap (disable by leaving empty in prod)
jwt_secret: "dev-change-me"
bootstrap_user: "admin"
bootstrap_password: "admin"

# ------------- controller ----------------

# config/controller-config.yaml - Controller configuration example
metrics_addr: ":9090"
probe_addr: ":9091"
enable_leader_election: true
leader_election_id: "a51c5837.codespace.dev"

# Certificate settings (for production)
metrics_cert_path: ""
metrics_cert_name: "tls.crt"
metrics_cert_key: "tls.key"
webhook_cert_path: ""
webhook_cert_name: "tls.crt"
webhook_cert_key: "tls.key"

# Security settings
secure_metrics: true
enable_http2: false

# Session settings
session_name_prefix: "cs-"
field_owner: "codespace-operator"
