{{- if and .Values.gateway.enabled .Values.gateway.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "codespace-operator.fullname" . }}-gateway
  {{- with .Values.gateway.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.gateway.ingress.className }}
  ingressClassName: {{ .Values.gateway.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.gateway.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.gateway.service.name | default (printf "%s-gateway" (include "codespace-operator.fullname" $)) }}
                port:
                  number: {{ $.Values.gateway.service.port }}
  {{- end }}
  {{- with .Values.gateway.ingress.tls }}
  tls:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
