{{- if and .Values.server.enabled .Values.server.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "codespace-operator.server.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
{{ include "codespace-operator.selectorLabels" (dict "name" (printf "%s-server" (include "codespace-operator.name" .)) "root" .) | indent 6 }}
  policyTypes: ["Ingress","Egress"]
  ingress:
  {{- if .Values.server.networkPolicy.allowIngressFromSameNamespace }}
    - from:
        - podSelector: {}   # allow same-namespace traffic (ingress controller/clients)
    - {}  # Allow all ingress for now to debug
  {{- else }}
    - {}
  {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow Kubernetes API access
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    # Allow all egress for debugging
    - to: []
{{- end }}