{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codespace-operator.server.name" . }}
  labels:
{{ include "codespace-operator.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "codespace-operator.selectorLabels" (dict "name" (printf "%s-server" (include "codespace-operator.name" .)) "root" .) | indent 6 }}
  template:
    metadata:
      labels:
{{ include "codespace-operator.selectorLabels" (dict "name" (printf "%s-server" (include "codespace-operator.name" .)) "root" .) | indent 8 }}
    spec:
      serviceAccountName: {{ if .Values.server.useManagerServiceAccount }}{{ include "codespace-operator.serviceAccountName" . }}{{ else }}{{ printf "%s-server" (include "codespace-operator.fullname" .) }}{{ end }}
      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: {{ .Values.server.service.gRPCPort | default 9090 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.server.probes.readinessPath | default "/readyz" }}
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: {{ .Values.server.probes.livenessPath | default "/healthz" }}
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          {{- with .Values.server.resources }}
          resources:
{{ toYaml . | indent 12 }}
          {{- end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
