apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codespace-operator.server.name" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "codespace-operator.labels" . | indent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.server.auth.jwtSecret | default (randAlphaNum 32) | b64enc }}
  bootstrap-user: {{ .Values.server.auth.bootstrapUser | default "admin" | b64enc }}
  bootstrap-password: {{ .Values.server.auth.bootstrapPassword | default (randAlphaNum 16) | b64enc }}
