{{- if and .Values.server.enabled (and (not .Values.server.useManagerServiceAccount) .Values.server.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "codespace-operator.server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "codespace-operator.labels" . | indent 4 }}
{{- end }}
