{{- if and .Values.server.enabled .Values.server.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "codespace-operator.server.name" . }}
  {{- with .Values.server.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.server.ingress.className }}
  ingressClassName: {{ .Values.server.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.server.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "codespace-operator.server.serviceName" $ }}
                port:
                  number: {{ $.Values.server.service.port }}
  {{- end }}
  {{- with .Values.server.ingress.tls }}
  tls:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
