# This rule is not used by the project codespace-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the codespace.codespace.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: codespace-operator
    app.kubernetes.io/managed-by: kustomize
  name: project-editor-role
rules:
  - apiGroups:
      - codespace.codespace.dev
    resources:
      - projects
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - codespace.codespace.dev
    resources:
      - projects/status
    verbs:
      - get
