rules:
  quoted-strings:
    # required: only-when-needed
    required: false
    allow-quoted-quotes: true
    extra-allowed: ["{|}"]
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true
