name: Notify Helm Charts (appVersion bump)

on:
  release:
    types: [published]

permissions:
  contents: read
  pull-requests: write

jobs:
  bump-appversion:
    if: startsWith(github.event.release.tag_name, 'codespace-')
    runs-on: ubuntu-latest
    steps:
      - name: Parse version
        id: ver
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "version=${TAG#app-v}" >> $GITHUB_OUTPUT

      - name: Checkout helm charts git repo
        uses: actions/checkout@v4
        with:
          repository: codespace-operator/charts
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Create branch and update Chart.yaml
        id: bump
        run: |
          set -e
          BRANCH="bump/appVersion-${{ steps.ver.outputs.version }}"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          git switch -c "$BRANCH"
          sudo apt-get update && sudo apt-get install -y yq
          yq -i '.appVersion = "${{ steps.ver.outputs.version }}"' charts/codespace-operator/Chart.yaml
          git add charts/codespace-operator/Chart.yaml
          git commit -m "chore(helm): bump appVersion to ${{ steps.ver.outputs.version }}"
          git push -u origin "$BRANCH"

      - name: Open PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HELM_REPO_TOKEN }}
          script: |
            const owner = 'codespace-operator'        // <- set your org
            const repo  = 'charts'                    // <- matches checkout
            const head  = `${owner}:${{ steps.bump.outputs.branch }}`
            const base  = 'main'
            const title = `chore(helm): bump appVersion to ${{ steps.ver.outputs.version }}`
            const body  = 'Sync appVersion with operator release.'
            await github.pulls.create({ owner, repo, title, head, base, body })
