name: Release Operator
on:
  push:
    branches: [main]
    paths:
      # - .github/release-config/release.operator.cjs
      - internal/**
      - cmd/**
      - ui/**
      - Dockerfile
      - go.mod
      - go.sum
      - "!CHANGELOG.*.md"
      - "!changelogs/CHANGELOG.*.md"

  workflow_dispatch: {}

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: >-
      github.event.head_commit != null &&
      !startsWith(github.event.head_commit.message, 'chore(release)') &&
      !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Fetch tags
        run: git fetch --tags --force --prune

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install release deps
        run: |
          npm i -D semantic-release @semantic-release/changelog @semantic-release/exec @semantic-release/git @semantic-release/github

      - name: Release Operator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release -e ./.github/release-config/release.operator.cjs
